ifndef S
S:=$(shell cd ../../../..; pwd)
endif
TARGET= ${S}/Targets/LS2K
SUBTARGET?=ls2k
CPPFLAGS=-mips3  -fcommon -fno-inline

%OBJS

%CFILES

%SFILES

%LOAD

export CFILES OBJS SFILES
include ${S}/Makefile.inc

%RULES
